
package com.siebel.orpos.order;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ORPOS_Order_WebService", targetNamespace = "http://siebel.com/ORPOS/Order", wsdlLocation = "file:/C:/ORPOSOrder.wsdl")
public class ORPOSOrderWebService
    extends Service
{

    private final static URL ORPOSORDERWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORPOSORDERWEBSERVICE_EXCEPTION;
    private final static QName ORPOSORDERWEBSERVICE_QNAME = new QName("http://siebel.com/ORPOS/Order", "ORPOS_Order_WebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/ORPOSOrder.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORPOSORDERWEBSERVICE_WSDL_LOCATION = url;
        ORPOSORDERWEBSERVICE_EXCEPTION = e;
    }

    public ORPOSOrderWebService() {
        super(__getWsdlLocation(), ORPOSORDERWEBSERVICE_QNAME);
    }

    public ORPOSOrderWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORPOSORDERWEBSERVICE_QNAME, features);
    }

    public ORPOSOrderWebService(URL wsdlLocation) {
        super(wsdlLocation, ORPOSORDERWEBSERVICE_QNAME);
    }

    public ORPOSOrderWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORPOSORDERWEBSERVICE_QNAME, features);
    }

    public ORPOSOrderWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ORPOSOrderWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ORPOSORDERPORT
     */
    @WebEndpoint(name = "ORPOS_ORDER_PORT")
    public ORPOSORDERPORT getORPOSORDERPORT() {
        return super.getPort(new QName("http://siebel.com/ORPOS/Order", "ORPOS_ORDER_PORT"), ORPOSORDERPORT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ORPOSORDERPORT
     */
    @WebEndpoint(name = "ORPOS_ORDER_PORT")
    public ORPOSORDERPORT getORPOSORDERPORT(WebServiceFeature... features) {
        return super.getPort(new QName("http://siebel.com/ORPOS/Order", "ORPOS_ORDER_PORT"), ORPOSORDERPORT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORPOSORDERWEBSERVICE_EXCEPTION!= null) {
            throw ORPOSORDERWEBSERVICE_EXCEPTION;
        }
        return ORPOSORDERWEBSERVICE_WSDL_LOCATION;
    }

}
