
package com.siebel.orpos.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ORPOS_ORDER_PORT", targetNamespace = "http://siebel.com/ORPOS/Order")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.orpos.order.ObjectFactory.class,
    com.siebel.xml.orpos_order_entry_io.data.ObjectFactory.class,
    com.siebel.xml.orpos_order_entry_io.id.ObjectFactory.class,
    com.siebel.xml.orpos_order_entry_io.query.ObjectFactory.class
})
public interface ORPOSORDERPORT {


    /**
     * 
     * @param orposQueryPageInput
     * @return
     *     returns com.siebel.orpos.order.ORPOSQueryPageOutput
     */
    @WebMethod(operationName = "ORPOS_QueryPage", action = "document/http://siebel.com/ORPOS/Order:ORPOS_QueryPage")
    @WebResult(name = "ORPOS_QueryPage_Output", targetNamespace = "http://siebel.com/ORPOS/Order", partName = "ORPOS_QueryPage_Output")
    public ORPOSQueryPageOutput orposQueryPage(
        @WebParam(name = "ORPOS_QueryPage_Input", targetNamespace = "http://siebel.com/ORPOS/Order", partName = "ORPOS_QueryPage_Input")
        ORPOSQueryPageInput orposQueryPageInput);

    /**
     * 
     * @param orposExecuteInput
     * @return
     *     returns com.siebel.orpos.order.ORPOSExecuteOutput
     */
    @WebMethod(operationName = "ORPOS_Execute", action = "document/http://siebel.com/ORPOS/Order:ORPOS_Execute")
    @WebResult(name = "ORPOS_Execute_Output", targetNamespace = "http://siebel.com/ORPOS/Order", partName = "ORPOS_Execute_Output")
    public ORPOSExecuteOutput orposExecute(
        @WebParam(name = "ORPOS_Execute_Input", targetNamespace = "http://siebel.com/ORPOS/Order", partName = "ORPOS_Execute_Input")
        ORPOSExecuteInput orposExecuteInput);

}
